# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paypalticketbookingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalbookingtransaction',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
