# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paypalbookingtransaction_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalblocktransaction',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
