# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paypalblocktransaction_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalbookingtransaction',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
