# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20171231_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalbookingtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
