# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20180102_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalblocktransaction',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paypalblocktransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
