# Generated by Django 2.2.6 on 2019-11-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_auto_20191123_0800'),
        ('payments', '0011_auto_20180104_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalGiftVoucherTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.GiftVoucherType')),
            ],
        ),
    ]
