# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='full name')),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('address', models.CharField(max_length=512)),
                ('postcode', models.CharField(max_length=10)),
                ('home_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(max_length=255)),
                ('emergency_contact1_name', models.CharField(max_length=255, verbose_name='name')),
                ('emergency_contact1_relationship', models.CharField(max_length=255, verbose_name='relationship')),
                ('emergency_contact1_phone', models.CharField(max_length=255, verbose_name='contact number')),
                ('emergency_contact2_name', models.CharField(max_length=255, verbose_name='name')),
                ('emergency_contact2_relationship', models.CharField(max_length=255, verbose_name='relationship')),
                ('emergency_contact2_phone', models.CharField(max_length=255, verbose_name='contact number')),
                ('medical_conditions', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you have any medical conditions which may require treatment or medication?')),
                ('medical_conditions_details', models.CharField(blank=True, max_length=2048, null=True)),
                ('joint_problems', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you suffer from problems regarding knee/back/shoulder/ankle/hip/neck?')),
                ('joint_problems_details', models.CharField(blank=True, max_length=2048, null=True)),
                ('allergies', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you have any allergies?')),
                ('allergies_details', models.CharField(blank=True, max_length=2048, null=True)),
                ('medical_treatment_terms', models.CharField(default='I confirm that I am over the age of 18', max_length=2048)),
                ('medical_treatment_permission', models.BooleanField()),
                ('disclaimer_terms', models.CharField(default='\n    I recognise that I may be asked to participate in some strenuous exercise\n    during the course and that such participation may present a heightened\n    risk of injury or ill health. All risks will be fully explained and I do\n    not hold The Watermelon Studio and any of their staff responsible for any\n    harm that may come to me should I decide to participate in such tasks. I\n    will not participate if pregnant and will update my teacher on any new\n    medical condition/injury throughout my time at The Watermelon Studio.\n    Other teachers/instructors may use the information submitted in this form\n    to help keep the chances of any injury to a minimum. I also hereby agree\n    to follow all rules set out by The Watermelon Studio.  I have\n    read and agree to the terms and conditions on the website.\n', max_length=2048)),
                ('terms_accepted', models.BooleanField()),
                ('over_18_statement', models.CharField(default='I confirm that I am over the age of 18', max_length=2048)),
                ('age_over_18_confirmed', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_disclaimer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_disclaimer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='disclaimer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Disclaimer',
        ),
    ]
