# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160128_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinedisclaimer',
            name='disclaimer_terms',
            field=models.CharField(default='I recognise that I may be asked to participate in some strenuous exercise during the course and that such participation may present a heightened risk of injury or ill health. All risks will be fully explained and I do NOT hold The Watermelon Studio and any of their staff responsible for any harm that may come to me should I decide to participate in such tasks. I knowingly assume all risks associated with participation, even if arising from negligence of the participants or others and assume full responsibility for my participation. I certify that I am in good physical condition can participate in the courses offered by The Watermelon Studio. I will not participate if pregnant and will update my teacher on any new medical condition/injury throughout my time at The Watermelon Studio.  I will not participate under the influence of drugs or alcohol. Other teachers/instructors may use the information submitted in this form to help keep the chances of any injury to a minimum. I also hereby agree to follow all rules set out by The Watermelon Studio.  I have read and agree to the terms and conditions on the website.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='onlinedisclaimer',
            name='medical_treatment_terms',
            field=models.CharField(default='I confirm that I am aged 18 or over', max_length=2048),
        ),
        migrations.AlterField(
            model_name='onlinedisclaimer',
            name='over_18_statement',
            field=models.CharField(default='I confirm that I am aged 18 or over', max_length=2048),
        ),
    ]
