# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-10 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160217_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinedisclaimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_disclaimer', to=settings.AUTH_USER_MODEL),
        ),
    ]
