# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170310_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinedisclaimer',
            name='disclaimer_terms',
            field=models.CharField(default="I recognise that I may be asked to participate in some strenuous exercise during the course and that such participation may present a heightened risk of injury or ill health. All risks will be fully explained and I do NOT hold The Watermelon Studio and any of their staff responsible for any harm that may come to me should I decide to participate in such tasks. I knowingly assume all risks associated with participation, even if arising from negligence of the participants or others and assume full responsibility for my participation. I certify that I am in good physical condition can participate in the courses offered by The Watermelon Studio. I will not participate if pregnant or if I have given birth within the previous 12 weeks and I will update my teacher on any new medical condition/injury throughout my time at The Watermelon Studio.  I will not participate under the influence of drugs or alcohol. Other teachers/instructors may use the information submitted in this form to help keep the chances of any injury to a minimum. I also hereby agree to follow all rules set out by The Watermelon Studio. I understand that photographs taken at the studio may be used on the studio's website and social media pages.  I have read and agree to the terms and conditions on the website.", max_length=2048),
        ),
    ]
