# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_update_disclaimer_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProtectionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048)),
                ('version', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignedDataProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_version', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_protection_agreement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='signeddataprotection',
            unique_together=set([('user', 'content_version')]),
        ),
    ]
