# Generated by Django 2.0.3 on 2018-03-18 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_data_protection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataprotectionpolicy',
            options={'verbose_name_plural': 'Data Protection Policies'},
        ),
        migrations.AddField(
            model_name='dataprotectionpolicy',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
