# Generated by Django 2.1.2 on 2019-03-24 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_nonregistereddisclaimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('address', models.CharField(max_length=512)),
                ('postcode', models.CharField(max_length=10)),
                ('home_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(max_length=255)),
                ('emergency_contact1_name', models.CharField(max_length=255, verbose_name='name')),
                ('emergency_contact1_relationship', models.CharField(max_length=255, verbose_name='relationship')),
                ('emergency_contact1_phone', models.CharField(max_length=255, verbose_name='contact number')),
                ('emergency_contact2_name', models.CharField(max_length=255, verbose_name='name')),
                ('emergency_contact2_relationship', models.CharField(max_length=255, verbose_name='relationship')),
                ('emergency_contact2_phone', models.CharField(max_length=255, verbose_name='contact number')),
                ('medical_conditions', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you have any medical conditions which may require treatment or medication?')),
                ('medical_conditions_details', models.CharField(blank=True, max_length=2048, null=True)),
                ('joint_problems', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you suffer from problems regarding knee/back/shoulder/ankle/hip/neck?')),
                ('joint_problems_details', models.CharField(blank=True, max_length=2048, null=True)),
                ('allergies', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you have any allergies?')),
                ('allergies_details', models.CharField(blank=True, max_length=2048, null=True)),
                ('medical_treatment_terms', models.CharField(default='I confirm that I am aged 18 or over', max_length=2048)),
                ('medical_treatment_permission', models.BooleanField()),
                ('disclaimer_terms', models.CharField(default="I recognise that I may be asked to participate in some strenuous exercise during the course and that such participation may present a heightened risk of injury or ill health. All risks will be fully explained and I do NOT hold The Watermelon Studio and any of their staff responsible for any harm that may come to me should I decide to participate in such tasks. I knowingly assume all risks associated with participation, even if arising from negligence of the participants or others and assume full responsibility for my participation. I certify that I am in good physical condition can participate in the courses offered by The Watermelon Studio. I will not participate if pregnant or if I have given birth within the previous 12 weeks 6 weeks or C-section in 12 weeks and I will update my teacher on any new medical condition/injury throughout my time at The Watermelon Studio.  I will not participate under the influence of drugs or alcohol. Other teachers/instructors may use the information submitted in this form to help keep the chances of any injury to a minimum. I also hereby agree to follow all rules set out by The Watermelon Studio. I understand that photographs taken at the studio may be used on the studio's website and social media pages.  I have read and agree to the terms and conditions on the website.", max_length=2048)),
                ('terms_accepted', models.BooleanField()),
                ('over_18_statement', models.CharField(default='I confirm that I am aged 18 or over', max_length=2048)),
                ('age_over_18_confirmed', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_archived', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
