# Generated by Django 3.0.3 on 2020-03-14 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisclaimerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer_terms', models.TextField()),
                ('medical_treatment_terms', models.TextField()),
                ('over_18_statement', models.TextField()),
                ('version', models.DecimalField(decimal_places=1, max_digits=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
