# Generated by Django 3.0.3 on 2020-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_disclaimercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='version',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonregistereddisclaimer',
            name='version',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='version',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
