# Generated by Django 3.0.3 on 2020-03-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_data_migration_v1_existing_disclaimers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveddisclaimer',
            name='disclaimer_terms',
        ),
        migrations.RemoveField(
            model_name='archiveddisclaimer',
            name='medical_treatment_terms',
        ),
        migrations.RemoveField(
            model_name='archiveddisclaimer',
            name='over_18_statement',
        ),
        migrations.RemoveField(
            model_name='nonregistereddisclaimer',
            name='disclaimer_terms',
        ),
        migrations.RemoveField(
            model_name='nonregistereddisclaimer',
            name='medical_treatment_terms',
        ),
        migrations.RemoveField(
            model_name='nonregistereddisclaimer',
            name='over_18_statement',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='disclaimer_terms',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='medical_treatment_terms',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='over_18_statement',
        ),
    ]
