# Generated by Django 3.0.3 on 2020-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_disclaimer_content_fields_from_signed_disclaimers'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclaimercontent',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
