# Generated by Django 3.2.7 on 2021-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210901_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonregistereddisclaimer',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
