# Generated by Django 4.1.1 on 2023-07-04 11:26

from django.db import migrations


def make_userprofiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("accounts", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userprofile'),
    ]

    operations = [
        migrations.RunPython(make_userprofiles, migrations.RunPython.noop),
    ]
