# Generated by Django 4.1.1 on 2023-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_userprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonregistereddisclaimer',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
