# Generated by Django 4.1.1 on 2023-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_nonregistereddisclaimer_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
