# Generated by Django 4.2.13 on 2024-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_userprofile_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="booking_preference",
            field=models.CharField(
                choices=[("membership", "membership"), ("block", "block")],
                default="membership",
                help_text="Use membership or block first for booking (if you have both available)",
            ),
        ),
    ]
