# Generated by Django 5.1.4 on 2025-01-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_userprofile_booking_preference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrintDisclaimer",
        ),
    ]
