from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from studioadmin.views import (ConfirmRefundView,
                               ConfirmPaymentView,
                               EventAdminUpdateView,
                               EventAdminCreateView,
                               EventRegisterListView,
                               TimetableListView,
                               )


urlpatterns = patterns('',
    url(r'^confirm-payment/(?P<pk>\d+)/$', ConfirmPaymentView.as_view(),
        name='confirm-payment'),
    url(r'^confirm-refunded/(?P<pk>\d+)/$', ConfirmRefundView.as_view(),
        name='confirm-refund'),
    url(r'^events/(?P<slug>[\w-]+)/edit$', EventAdminUpdateView.as_view(),
        {'ev_type': 'events'}, name='edit_event'),
    url(r'^events/$', 'studioadmin.views.event_admin_list',
        {'ev_type': 'events'}, name='events'),
    url(r'^event-registers/$', EventRegisterListView.as_view(),
        {'ev_type': 'events'}, name='event_register_list'),
    url(r'^event-registers/(?P<event_slug>[\w-]+)/(?P<status_choice>[\w-]+)$',
        'studioadmin.views.register_view', name='event_register'),
    url(r'^event-registers/(?P<event_slug>[\w-]+)/(?P<status_choice>[\w-]+)/print/$',
        'studioadmin.views.register_view', {'print': True}, name='event_register_print'),
    url(r'^events/new/$', EventAdminCreateView.as_view(),
        {'ev_type': 'event'}, name='add_event'),
    url(r'^classes/(?P<slug>[\w-]+)/edit$', EventAdminUpdateView.as_view(),
        {'ev_type': 'lessons'}, name='edit_lesson'),
    url(r'^classes/$', 'studioadmin.views.event_admin_list',
        {'ev_type': 'lessons'}, name='lessons'),
    url(r'^class-registers/$', EventRegisterListView.as_view(),
        {'ev_type': 'lessons'}, name='class_register_list'),
    url(r'^class-registers/(?P<event_slug>[\w-]+)/(?P<status_choice>[\w-]+)$',
        'studioadmin.views.register_view', name='class_register'),
    url(r'^class-registers/(?P<event_slug>[\w-]+)/(?P<status_choice>[\w-]+)/print/$',
        'studioadmin.views.register_view', {'print': True}, name='class_register_print'),
    url(r'^classes/new/$', EventAdminCreateView.as_view(),
        {'ev_type': 'lesson'}, name='add_lesson'),
    url(r'^$', RedirectView.as_view(url='/studioadmin/classes/', permanent=True)),
    )
