# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 12:19
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_auto_20151231_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=['name', 'date'], unique=True),
        ),
    ]
