# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_auto_20160131_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booking.Block'),
        ),
    ]
