# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_block_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': (('can_request_free_class', 'Can request free class and pole practice'), ('is_regular_student', 'Is regular student'), ('can_view_registers', 'Can view registers'))},
        ),
    ]
