# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_auto_20160202_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_show',
            field=models.BooleanField(default=False, help_text='Student paid but did not attend'),
        ),
    ]
