# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='paypal_email',
            field=models.EmailField(default='test-paypal@watermelon.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='paypal_email',
            field=models.EmailField(default='test-paypal@watermelon.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AddField(
            model_name='ticketedevent',
            name='paypal_email',
            field=models.EmailField(default='test-paypal@watermelon.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
    ]
