# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_auto_20160310_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocktype',
            options={'ordering': ('event_type__subtype', 'size')},
        ),
        migrations.AddField(
            model_name='block',
            name='transferred_booking_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
