# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0047_auto_20160413_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(help_text='Enter a number between 1 and 99')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('max_vouchers', models.PositiveIntegerField(blank=True, help_text='Maximum uses across all users', null=True, verbose_name='Maximum available vouchers')),
                ('max_per_user', models.PositiveIntegerField(blank=True, default=1, help_text='Maximum times this voucher can be used by a single user', null=True, verbose_name='Maximum uses per user')),
            ],
        ),
        migrations.CreateModel(
            name='UsedBlockVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedEventVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BaseVoucher')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('block_types', models.ManyToManyField(to='booking.BlockType')),
            ],
            bases=('booking.basevoucher',),
        ),
        migrations.CreateModel(
            name='EventVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BaseVoucher')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('event_types', models.ManyToManyField(to='booking.EventType')),
            ],
            bases=('booking.basevoucher',),
        ),
        migrations.AddField(
            model_name='usedeventvoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.EventVoucher'),
        ),
        migrations.AddField(
            model_name='usedblockvoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BlockVoucher'),
        ),
    ]
