# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_data_migration_voucher_to_eventvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='event_types',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='users',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
