# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_auto_20160707_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
