# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_auto_20161103_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auto_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
