# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_booking_auto_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='extended_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
