# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-23 10:23
from __future__ import unicode_literals

from django.db import migrations


def update_location(apps, schema_editor):
    # We can't import the Event model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model("booking", "Event")
    for event in Event.objects.filter(location__icontains='watermelon'):
        event.location = "Beaverbank Place"
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_block_extended_expiry_date'),
    ]

    operations = [
        migrations.RunPython(update_location, migrations.RunPython.noop)
    ]
