# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_datamigration_edit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Beaverbank Place', 'The Watermelon Studio - Beaverbank Place'), ("Davidson's Mains", "The Watermelon Studio - Davidson's Mains")], default='Beaverbank Place', max_length=255),
        ),
    ]
