# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_new_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paypal_pending',
            field=models.BooleanField(default=False),
        ),
    ]
