# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_booking_paypal_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='paypal_pending',
            field=models.BooleanField(default=False),
        ),
    ]
