# Generated by Django 2.1.2 on 2019-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_auto_20181018_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='assign_free_class_on_completion',
            field=models.BooleanField(default=False),
        ),
    ]
