# Generated by Django 2.2.6 on 2019-11-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_blocktype_assign_free_class_on_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_warning_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='date_warning_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
