# Generated by Django 2.2.6 on 2019-11-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_auto_20191123_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvouchertype',
            name='active',
            field=models.BooleanField(default=True, help_text='Display on site; set to False instead of deleting unused voucher types'),
        ),
    ]
