# Generated by Django 2.2.6 on 2019-11-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_auto_20191116_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevoucher',
            name='is_gift_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
