# Generated by Django 2.2.6 on 2019-12-04 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_giftvouchertype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
