# Generated by Django 2.2.6 on 2019-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_basevoucher_is_gift_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevoucher',
            name='message',
            field=models.TextField(blank=True, help_text='Message (max 500 characters', max_length=500, null=True),
        ),
    ]
