# Generated by Django 2.2.6 on 2019-11-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_basevoucher_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevoucher',
            name='purchaser_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='basevoucher',
            name='message',
            field=models.TextField(blank=True, help_text='Message (max 500 characters)', max_length=500, null=True),
        ),
    ]
