# Generated by Django 3.0.3 on 2020-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktype',
            name='paypal_email',
            field=models.EmailField(default='thewatermelonstudio@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='paypal_email',
            field=models.EmailField(default='thewatermelonstudio@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AlterField(
            model_name='ticketedevent',
            name='paypal_email',
            field=models.EmailField(default='thewatermelonstudio@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
    ]
