# Generated by Django 3.0.3 on 2020-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0070_event_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Beaverbank Place', 'The Watermelon Studio - Beaverbank Place'), ('Online', 'Online'), ("Davidson's Mains", "The Watermelon Studio - Davidson's Mains")], default='Beaverbank Place', max_length=255),
        ),
    ]
