# Generated by Django 3.0.3 on 2020-05-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_auto_20200523_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Used for auto-assigned free classes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booking.Block'),
        ),
    ]
