# Generated by Django 3.0.3 on 2020-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0073_auto_20201213_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(choices=[('CL', 'Class'), ('EV', 'Event'), ('OT', 'Online tutorial'), ('RH', 'Room hire')], help_text="This determines whether events of this type are listed on the 'Classes', 'Workshops', 'Tutorials', 'Room Hire' pages", max_length=2),
        ),
    ]
