# Generated by Django 3.0.3 on 2021-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0074_auto_20201216_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(default='info@thewatermelonstudio.co.uk', max_length=254),
        ),
        migrations.AlterField(
            model_name='ticketedevent',
            name='contact_email',
            field=models.EmailField(default='info@thewatermelonstudio.co.uk', max_length=254),
        ),
    ]
