# Generated by Django 3.0.3 on 2021-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0075_auto_20210220_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketedevent',
            name='contact_person',
            field=models.CharField(default='Gwen Holbrey', max_length=255),
        ),
    ]
