# Generated by Django 3.0.3 on 2021-04-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0076_auto_20210301_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_on_site',
            field=models.BooleanField(default=True),
        ),
    ]
