# Generated by Django 3.1.12 on 2021-09-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0077_event_visible_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='instructor_confirmed_no_show',
            field=models.BooleanField(default=False, help_text='Marked as no-show by instructor (confirmed no-show, not late cancellation)'),
        )
    ]
