# Generated by Django 3.2.8 on 2022-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0078_instructor_confirmed_no_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Number of weeks until block expires', null=True),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Number of months until block expires', null=True),
        ),
    ]
