# Generated by Django 3.2.8 on 2022-01-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0079_auto_20220119_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktype',
            name='paypal_email',
            field=models.EmailField(default='dummy-email@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='paypal_email',
            field=models.EmailField(default='dummy-email@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AlterField(
            model_name='ticketedevent',
            name='paypal_email',
            field=models.EmailField(default='dummy-email@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
    ]
