# Generated by Django 4.1.1 on 2023-07-27 16:38

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0082_banner_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Filter categories',
            },
        ),
        migrations.AddConstraint(
            model_name='filtercategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category'), name='unique_lower_category'),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='booking.filtercategory'),
        ),
    ]
