# Generated by Django 4.1.1 on 2023-09-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0001_initial'),
        ('booking', '0083_filtercategory_filtercategory_unique_lower_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevoucher',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basevoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='stripe_payments.invoice'),
        ),
        migrations.AddField(
            model_name='block',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='stripe_payments.invoice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='stripe_payments.invoice'),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_bookings', to='stripe_payments.invoice'),
        ),
    ]
