# Generated by Django 4.1.1 on 2023-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0084_basevoucher_checkout_time_basevoucher_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktype',
            name='paypal_email',
            field=models.EmailField(default='thewatermelonstudio@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='paypal_email',
            field=models.EmailField(default='thewatermelonstudio@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
        migrations.AlterField(
            model_name='ticketedevent',
            name='paypal_email',
            field=models.EmailField(default='thewatermelonstudio@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
    ]
