# Generated by Django 4.1.1 on 2023-09-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0087_remove_basevoucher_invoice_blockvoucher_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['user__username', 'id']},
        ),
    ]
