# Generated by Django 4.1.1 on 2023-12-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0089_ticketedeventwaitinglistuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Optional description of permitted group, e.g. "only available to regular students"', max_length=255, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_group',
            field=models.ForeignKey(blank=True, help_text='Override group allowed to book this event (leave blank to inherit permissions from event type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='booking.allowedgroup'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='allowed_group',
            field=models.ForeignKey(blank=True, help_text='Group allowed to book this type of event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='booking.allowedgroup'),
        ),
    ]
