# Generated by Django 4.1.1 on 2023-12-26 10:56

from django.db import migrations


def migrate_permissions(apps, schema_editor):
    # We can't import the EventType or Group model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    EventType = apps.get_model("booking", "EventType")
    Event = apps.get_model("booking", "Event")
    AllowedGroup = apps.get_model("booking", "AllowedGroup")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    pp_group, _ = Group.objects.get_or_create(name="regular student")
    allowed_pp_group, _ = AllowedGroup.objects.get_or_create(group=pp_group, description="only available to regular students")

    default_group, _ = Group.objects.get_or_create(name="_open to all")
    allowed_default_group, _ = AllowedGroup.objects.get_or_create(group=default_group, description="default group; open to all")
    
    pp_event_types = EventType.objects.filter(subtype="Pole practice")
    other_event_types = EventType.objects.exclude(subtype="Pole practice")
    if pp_event_types.exists():
        pole_practice = pp_event_types.first()
        pole_practice.allowed_group = allowed_pp_group
        pole_practice.save()

        permission = Permission.objects.get(codename="is_regular_student")
        users = permission.user_set.all()
        for user in users:
            user.groups.add(pp_group)

    for event_type in other_event_types:
        event_type.allowed_group = allowed_default_group
        event_type.save()

    for event in Event.objects.all():
        event.allowed_group = event.event_type.allowed_group
        event.save()


def reverse_pole_practice_permissions(apps, schema_editor):
    # We can't import the EventType or Group model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AllowedGroup = apps.get_model("booking", "AllowedGroup")
    Permission = apps.get_model("auth", "Permission")

    allowed_group = AllowedGroup.objects.filter(group__name="regular student")
    if allowed_group.exists():
        group = allowed_group.first().group
        permission, _ = Permission.objects.get_or_create(codename="is_regular_student")
        users = group.user_set.all()
        for user in users:
            user.user_permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0090_allowedgroup_event_allowed_group_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_permissions, reverse_code=reverse_pole_practice_permissions),
    ]
