# Generated by Django 4.1.1 on 2023-12-29 12:04

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0091_datamigration_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedgroup',
            options={'ordering': ('group__name',)},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ('event_type', 'subtype')},
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_group_override',
            field=models.ForeignKey(blank=True, help_text='Override group allowed to book this event (defaults to same group as the event type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='booking.allowedgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allowed_group',
            field=models.ForeignKey(blank=True, help_text='Override group allowed to book this event (defaults to same group as the event type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='booking.allowedgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_time_allowed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of hours allowed for payment after booking (after this bookings will be cancelled.)', null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='allowed_group',
            field=models.ForeignKey(default=booking.models.get_default_allowed_group_id, help_text='Group allowed to book this type of event', on_delete=models.SET(booking.models.get_default_allowed_group), related_name='event_types', to='booking.allowedgroup'),
        ),
    ]
