# Generated by Django 4.1.1 on 2024-01-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0093_remove_event_allowed_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='hide',
            field=models.BooleanField(default=False, help_text='Hide this event type from admin forms and lists'),
        ),
    ]
