# Generated by Django 4.1.1 on 2024-05-19 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0095_remove_event_location_index_alter_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('stripe_product_id', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_price_id', models.TextField(null=True)),
                ('active', models.BooleanField(default=True, help_text='Visible and available for purchase on site')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.TextField(null=True)),
                ('subscription_status', models.TextField(null=True)),
                ('customer_id', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number allowed per month; leave blank for unlimited', null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.eventtype')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_items', to='booking.membership')),
            ],
            options={
                'unique_together': {('membership', 'event_type')},
            },
        ),
    ]
