# Generated by Django 4.2.13 on 2024-06-09 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0096_membership_usermembership_membershipitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermembership',
            options={'ordering': ('subscription_status', '-start_date')},
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.usermembership'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_billing_cycle_anchor',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='booking.membership'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
