# Generated by Django 4.2.13 on 2024-05-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0096_membership_usermembership_membershipitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.usermembership'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
