# Generated by Django 4.2.13 on 2024-06-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0097_alter_usermembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='pending_setup_intent',
            field=models.TextField(null=True),
        ),
    ]
