# Generated by Django 4.2.13 on 2024-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0098_usermembership_pending_setup_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Visible and available for purchase on site"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="active",
            field=models.BooleanField(default=True, help_text="Active on Stripe"),
        ),
        migrations.AlterField(
            model_name="membershipitem",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Number allowed per month", null=True
            ),
        ),
    ]
