# Generated by Django 4.2.13 on 2024-07-21 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0098_usermembership_pending_setup_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Visible and available for purchase on site"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="active",
            field=models.BooleanField(default=True, help_text="Active on Stripe"),
        ),
        migrations.AlterField(
            model_name="membershipitem",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Number allowed per month", null=True
            ),
        ),
        migrations.CreateModel(
            name="StripeSubscriptionVoucher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9]+$", message="Alphanumeric characters only"
                            )
                        ],
                    ),
                ),
                ("promo_code_id", models.CharField(max_length=255)),
                ("amount_off", models.PositiveIntegerField(blank=True, null=True)),
                ("percent_off", models.FloatField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("once", "once"),
                            ("forever", "forever"),
                            ("repeating", "repeating"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "duration_in_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("redeem_by", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "memberships",
                    models.ManyToManyField(
                        related_name="memberships", to="booking.membership"
                    ),
                ),
            ],
        ),
    ]
