# Generated by Django 4.2.13 on 2024-07-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0099_membership_visible_alter_membership_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscriptionvoucher",
            name="new_memberships_only",
            field=models.BooleanField(
                default=True, help_text="Valid for new memberships only"
            ),
        ),
    ]
