# Generated by Django 4.2.13 on 2024-08-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0102_alter_membership_options_basevoucher_members_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocktype",
            name="assign_free_class_on_completion",
        ),
        migrations.AlterField(
            model_name="block",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Previously used for auto-assigned free classes; kept for historic reasons",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="booking.block",
            ),
        ),
    ]
