# Generated by Django 4.2.13 on 2024-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0103_remove_blocktype_assign_free_class_on_completion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="members_only",
            field=models.BooleanField(
                default=False, help_text="Can only be booked by members"
            ),
        ),
    ]
