# Generated by Django 5.1.4 on 2025-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0105_alter_stripesubscriptionvoucher_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermembership",
            name="override_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Set a manual start date; must be the 1st of a month. Actual start date from Stripe will be ignored. Note that this affects users' ability to book classes ONLY, not payments. Changing this date will not update any bookings that have already been made.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usermembership",
            name="override_subscription_status",
            field=models.TextField(
                blank=True,
                help_text="Set a manual subscription status; usually this will be used only to manually make a subscriptionpaused. Note that this affects users' ability to book classes ONLY, not payments. To also pausepayment, you need to add a 100% discount to the subscription for the relevant number of months.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="pending_setup_intent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
