# Generated by Django 4.1.1 on 2023-09-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_stripe_test',
            field=models.BooleanField(default=False),
        ),
    ]
