# Generated by Django 4.2.13 on 2024-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payments", "0004_alter_stripesubscriptioninvoice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscriptioninvoice",
            name="promo_code_id",
            field=models.CharField(null=True),
        ),
    ]
