# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20151116_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='payment_time_allowed',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Number of hours allowed for payment after booking (after this bookings will be cancelled.  Note that the automatic cancel job allows 6 hours after booking, so 6 hours is the minimum time that will be applied.', null=True),
        ),
    ]
