# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-23 10:34
from __future__ import unicode_literals

from django.db import migrations


def update_location(apps, schema_editor):
    # We can't import the Event model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Session = apps.get_model("timetable", "Session")
    for session in Session.objects.filter(location__icontains='watermelon'):
        session.location = "Beaverbank Place"
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_session_paypal_email'),
    ]

    operations = [
        migrations.RunPython(update_location, migrations.RunPython.noop)
    ]
