# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_datamigration_edit_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(choices=[('Beaverbank Place', 'The Watermelon Studio - Beaverbank Place'), ("Davidson's Mains", "The Watermelon Studio - Davidson's Mains")], default='Beaverbank Place', max_length=255),
        ),
    ]
