# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-23 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_datamigration_edit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(choices=[('Beaverbank Place', 'The Watermelon Studio - Beaverbank Place'), ('New Location', 'The Watermelon Studio - New Location')], default='Beaverbank Place', max_length=255),
        ),
    ]
