# Generated by Django 2.0.3 on 2018-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_new_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='contact_person',
            field=models.CharField(default='Gwen Holbrey', max_length=255),
        ),
    ]
