# Generated by Django 2.1.2 on 2018-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20180722_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=8.5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_time_allowed',
            field=models.PositiveIntegerField(blank=True, default=6, help_text='Number of hours allowed for payment after booking (after this bookings will be cancelled.  Note that the automatic cancel job allows 6 hours after booking, so 6 hours is the minimum time that will be applied.', null=True),
        ),
    ]
