# Generated by Django 3.0.3 on 2020-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_auto_20181126_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='paypal_email',
            field=models.EmailField(default='thewatermelonstudio@hotmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
    ]