# Generated by Django 3.0.3 on 2020-05-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_auto_20200228_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(choices=[('Beaverbank Place', 'The Watermelon Studio - Beaverbank Place'), ('Online', 'Online'), ("Davidson's Mains", "The Watermelon Studio - Davidson's Mains")], default='Beaverbank Place', max_length=255),
        ),
    ]
