# Generated by Django 3.0.3 on 2021-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_auto_20200523_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='contact_email',
            field=models.EmailField(default='info@thewatermelonstudio.co.uk', max_length=254),
        ),
    ]
