# Generated by Django 4.1.1 on 2023-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0083_filtercategory_filtercategory_unique_lower_category_and_more'),
        ('timetable', '0021_auto_20210220_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='categories',
            field=models.ManyToManyField(to='booking.filtercategory'),
        ),
    ]
