# Generated by Django 4.1.1 on 2024-01-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_session_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='payment_time_allowed',
            field=models.PositiveIntegerField(blank=True, default=4, help_text='Number of hours allowed for payment after booking (after this bookings will be cancelled.)', null=True),
        ),
    ]
