# Generated by Django 4.1.1 on 2024-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_alter_session_payment_time_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='location_index',
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(choices=[('Main Studio', 'Main Studio'), ('Pip Studio', 'Pip Studio'), ('Beaverbank Place', 'The Watermelon Studio - Beaverbank Place'), ('Online', 'Online'), ("Davidson's Mains", "The Watermelon Studio - Davidson's Mains")], default='Main Studio', max_length=255),
        ),
    ]
